print(*[f'{1} * {i} = {1 * i}' for i in range(1,11)], sep='\n')
print("\n")
print(*[f'{2} * {i} = {2 * i}' for i in range(1,11)], sep='\n')
print("\n")
print(*[f'{3} * {i} = {3 * i}' for i in range(1,11)], sep='\n')
print("\n")
print(*[f'{4} * {i} = {4 * i}' for i in range(1,11)], sep='\n')
print("\n")
print(*[f'{5} * {i} = {5 * i}' for i in range(1,11)], sep='\n')
print("\n")
print(*[f'{6} * {i} = {6 * i}' for i in range(1,11)], sep='\n')
print("\n")
print(*[f'{7} * {i} = {7 * i}' for i in range(1,11)], sep='\n')
print("\n")
print(*[f'{8} * {i} = {8 * i}' for i in range(1,11)], sep='\n')
print("\n")
print(*[f'{9} * {i} = {9 * i}' for i in range(1,11)], sep='\n')
print("\n")
print(*[f'{10} * {i} = {10 * i}' for i in range(1,11)], sep='\n')
print("\n")